[supervisord]
nodaemon=true

[program:queue.event.communications.send]
process_name=%(program_name)s_%(process_num)02d
command=php artisan queue:work rabbitmq --queue=queue.event.communications.send
stdout_logfile=/var/www/html/storage/logs/worker.log
autostart=true
autorestart=true
numprocs=1
redirect_stderr=true
stopwaitsecs=3600
